server:
  port: 80  #服务端口

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: Alex2017!
      driver-class-name: com.mysql.jdbc.Driver
  application:
    name: springBase  #服务名

mybatis:
  config-locations: classpath:mybatis-config.xml
  mapper-locations: classpath:com/mgp/*/dao/*.xml