#选择配置文件配置
spring:
  profiles:
    active: dev

#公共配置

#log4j2
logging:
  config: classpath:log4j2.xml
#集成mybatis
mybatis:
  mapperLocations: classpath*:com/mgp/*/dao/*.xml
  configLocation: classpath:mybatis-config.xml
#google验证码
kaptcha:
  session:
    key: kaptcha.code
  obscurificator:
    impl: com.google.code.kaptcha.impl.ShadowGimpy
  noise:
    impl: com.google.code.kaptcha.impl.NoNoise
  image:
    width: 90
    height: 33
  textproducer:
    font:
      size: 26
      color: black
    char:
      length: 4
      space: 5

  background:
    clear:
      from: 247,247,247
      to: 247,247,247